<html>
<head>
 <title>Third Annual Upstate Number Theory Conference</title>
 <link rel="stylesheet" type="text/css" href="http://www.math.binghamton.edu/ntconf/mainStyle.css" />
</head>
<body>
<div id="header">
 <h1 align="center"> Third Annual Upstate New York Number Theory Conference</h1>
 <h2 align="center">Binghamton University, April 26 - 28, 2013</h2>
</div>
<div id="navbar">
	<ul>
		<li><a href="http://www.math.binghamton.edu/ntconf/index.html">Home</a></li>
		<li><a href="http://www.math.binghamton.edu/ntconf/schedule.html">Schedule/Abstracts</a></li>
		<li><a href="http://www.math.binghamton.edu/ntconf/hotels.html">Hotels</a>
		<li><a href="http://www.math.binghamton.edu/ntconf/contact.html">Contact</a></li>
		<!--li><a href="http://www.math.binghamton.edu/ntconf/cgi-bin/registration2013.cgi">Registration</a></li-->
		<li><a href="http://www.math.binghamton.edu/ntconf/organizers.html">Organizers</a></li>
		<li><a href="http://www.math.binghamton.edu/ntconf/UpstateNTConf_2013.pdf">Poster</a></li>
	</ul>

 <!--Home, Contact-->
 <!-- Speakers,registration -->
 <!-- schedule, directions -->

</div>
<div id="content">
 <hr />
	<!-- #include -->
 <hr />
</div>
<div id="footer">
 <p>  
  The Third Annual Upstate New York Number Theory Conference is funded by 
  the National Science Foundation Award #1100033
  and the department of mathematics at Binghamton University.  
 </p>
</div>
</body>
</html>
